---
title: "Passwords"
author: "Donald VM | @goldblatchickens"
output: html_notebook
---
# Setup
```{r}
library(tidyverse)
```

## Data
```{r}
passwords <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-01-14/passwords.csv')
```
# Numbers
```{r}
passwords %>% group_by(category) %>% summerise(mean = mean(strength), sd = sd(strength))
```

# Plot
```{r plot}
p<-passwords %>% 
select(password,category, value, strength) %>%
mutate(length = nchar(password)) %>%
filter(strength > 10) %>% 
  arrange(desc(strength)) %>% 
  ggplot(., mapping = aes(x = length, y = strength, color = category, label = password ))+
  geom_point() + 
  theme_minimal()+
  theme(plot.background = element_rect(fill = "aliceblue"))
  
p + geom_label(size = 5,fontface = "bold", nudge_x = -0.1) + labs(title = "Strength VS Length", subtitle = "For Strength > 10, notice all of them are combinations of numbers and letters.", caption = 'Source: Paswords | #TidyTuesday #R4DS') +theme(legend.position="bottom")+theme(legend.background = element_rect(fill="white", 
                                  size=0.5, linetype="solid")) +
  theme(legend.title = element_text(colour="black", size=14, 
                                      face="bold"))

```

Help: 

http://www.sthda.com/english/wiki/ggplot2-texts-add-text-annotations-to-a-graph-in-r-software

labels:
https://ggplot2.tidyverse.org/reference/geom_text.html

to play with the legend: http://www.sthda.com/english/wiki/wiki.php?title=ggplot2-legend-easy-steps-to-change-the-position-and-the-appearance-of-a-graph-legend-in-r-software

color names: https://www.r-graph-gallery.com/42-colors-names.html

